packages:
  - packages/**
  - examples/**

catalog:
  '@types/body-parser': 1.19.6
  '@types/cors': 2.8.19
  '@types/express': 5.0.3
  body-parser: ^2.2.0
  cors: ^2.8.5
  express: 5.1.0
  pkgroll: 2.14.5
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: 3.2.4
  zod: ^4.0.10

onlyBuiltDependencies:
  - esbuild
